### PR TITLE
Refactor / fix delivery api ad schedule typings

### LINKED ISSUE #472: AdSchedule type doesn't match actual data type
In the `Player.tsx`, an `adsData` prop uses the `AdSchedule` type. This type is defined as follows:

```ts
export type AdSchedule = {
  adscheduleid?: string;
  client: string;
  schedule: string;
};
```

However, the data seems to differ from the type above:

```json
{
    "rules": {
        "startOnSeek": "pre",
        "timeBetweenAds": 0
    },
    "client": "vast",
    "schedule": [
        {
            "tag": [
                "https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_preroll_skippable&sz=640x480&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=__random-number__"
            ],
            "type": "linear",
            "offset": "pre",
            "skipoffset": 5
        }
    ],
    "adscheduleid": "S2FKhc4J"
}
```

### PR DESCRIPTION
**Pull request by ChristiaanScheermeijer**
## Description

This PR changes the adSchedule typings to include the correct typings when served from the delivery API.

Fixes #472

### CODE REVIEW

**Comment by ChristiaanScheermeijer** [comment]
@dbudzins @AntonLantukh what do you think? 😄

File: packages/hooks-react/src/useAds.ts [hunk 1]
```diff
@@ -33,12 +34,12 @@ export const useAds = ({ mediaId }: { mediaId: string }) => {
...
   const { data: adSchedule, isLoading: isAdScheduleLoading } = useLegacyStandaloneAds({ adScheduleId, enabled: !!adScheduleId });
   const adConfig = useAdConfigFlow
-    ? {
+    ? ({
         client: 'vast',
         schedule: createURL(adScheduleUrls?.xml || '', {
           media_id: mediaId,
         }),
-      }
+      } as AdSchedule)
```
Comment (AntonLantukh) [inline packages/hooks-react/src/useAds.ts]: Can we rename it to AdConfig and use the following type:

```
export type AdConfig = {
  client: string;
  schedule: string;
};
```

And then we could use AdSchedule instead of DeliveryAdSchedule

Comment (ChristiaanScheermeijer) [reply packages/hooks-react/src/useAds.ts]: Sure! I also considered something like this, but didn't changed it because both types are actually ad configs containing schedules.

File: packages/hooks-react/src/useAds.ts [hunk 2]
```diff
@@ -33,12 +34,12 @@ export const useAds = ({ mediaId }: { mediaId: string }) => {
...
   const { data: adSchedule, isLoading: isAdScheduleLoading } = useLegacyStandaloneAds({ adScheduleId, enabled: !!adScheduleId });
   const adConfig = useAdConfigFlow
-    ? {
+    ? ({
         client: 'vast',
         schedule: createURL(adScheduleUrls?.xml || '', {
           media_id: mediaId,
         }),
-      }
+      } as AdConfig)
```
Comment (AntonLantukh) [inline packages/hooks-react/src/useAds.ts:42]: Do you think we can also remove this one? Looks like there are no errors.

Comment (ChristiaanScheermeijer) [reply packages/hooks-react/src/useAds.ts:42]: I thought the data typing was a bit clearer when forcing it to `AdConfig`. Without it infers the typings and looks like this:

```ts
function useAds({mediaId}: {mediaId: string}): {isLoading: false | true, data: {schedule: string, client: string} | undefined | AdSchedule}
```

VS

```ts
function useAds({mediaId}: {mediaId: string}): {isLoading: false | true, data: AdConfig | undefined | AdSchedule}
```

Without the typing, it still satisfies to `AdConfig` though...

**Review by AntonLantukh — APPROVED** [review]
