### PR TITLE
fix(playlist): fix empty recommendations

### LINKED ISSUE #234: Related videos still shows up, when there is no recommendations playlists

### PR DESCRIPTION
**Pull request by AntonLantukh**
## Description

- Don't show a placehilder when to playlist id is set

This PR solves # .

### Steps completed:

According to our definition of done, I have completed the following steps:

- [ ] Acceptance criteria met
- [ ] Unit tests added
- [ ] Docs updated (including config and env variables)
- [ ] Translations added
- [ ] UX tested
- [ ] Browsers / platforms tested
- [ ] Rebased & ready to merge without conflicts
- [ ] Reviewed own code

### CODE REVIEW

File: test-e2e/tests/home_test.ts [hunk 1]
```diff
@@ -147,5 +147,5 @@ Scenario('I can see the footer', ({ I }) => {
   I.see('jwplayer.com');
   I.click('jwplayer.com');
   I.switchToNextTab();
-  I.seeCurrentUrlEquals('https://www.jwplayer.com/');
```
Comment (budzworthy) [inline test-e2e/tests/home_test.ts:150]: Any idea why this changed?

**Review by budzworthy — APPROVED** [review]

File: test-e2e/tests/home_test.ts (hunk 1 above)
Comment (AntonLantukh) [reply test-e2e/tests/home_test.ts:150]: It seems that we have updated our website recently :)
Have a look: https://jwplayer.com/
